version: '3.8'

services:
  # The Python Automation Engine
  job-bot-backend:
    build:
      context: ./backend  # Tells Docker to look in the backend folder
      dockerfile: Dockerfile
    container_name: job_bot_backend
    volumes:
      - ./backend:/app    # Syncs your code so changes update instantly
      - ./backend/resumes:/app/resumes # Keeps your resumes accessible
      - ./backend/screenshots:/app/screenshots # Added this line to persist screenshots
    env_file:
      - ./backend/.env    # Loads your API keys and Workday passwords
    restart: always       # Restarts if the Mini PC reboots
    stdin_open: true      # Allows you to interact with the "input()" pauses
    tty: true
    # If you want it to run on a schedule, we keep it running:
    command: python main_loop.py